//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A9: return "D1 - Injector 2";
		case Gpio::C13: return "A1 - Coil 1";
		case Gpio::C6: return "G4 - LS Output 3";
		case Gpio::D10: return "B1 - LS Output 1 / Injector 4";
		case Gpio::D11: return "C1 - Injector 3";
		case Gpio::D13: return "G3 - LS Output 2";
		case Gpio::D2: return "A4 - Tach Output";
		case Gpio::D3: return "E1 - Injector 1";
		case Gpio::E1: return "F2 - Trigger Input";
		case Gpio::E12: return "E3 - CMP 1 / HALL Input";
		case Gpio::E13: return "D2 - Digital Input 1";
		case Gpio::E14: return "D3 - Digital Input 2";
		case Gpio::E15: return "D4 - Digital Input 3";
		case Gpio::E4: return "A3 - Coil 3";
		case Gpio::E5: return "A2 - Coil 2";
		default: return nullptr;
	}
	return nullptr;
}
