//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

#define PIN_A1 MM100_IGN1
#define PIN_A2 MM100_IGN2
#define PIN_A3 MM100_IGN3
#define PIN_A4 MM100_INJ5
#define PIN_B1 MM100_INJ4
#define PIN_B2 MM100_IN_IAT_ANALOG
#define PIN_B3 MM100_IN_CLT_ANALOG
#define PIN_B4 MM100_IN_MAP1_ANALOG
#define PIN_C1 MM100_INJ3
#define PIN_C2 MM100_IN_TPS_ANALOG
#define PIN_C3 MM100_IN_O2S_ANALOG
#define PIN_C4 MM100_IN_O2S2_ANALOG
#define PIN_D1 MM100_INJ2
#define PIN_D2 MM100_IN_D2
#define PIN_D3 MM100_IN_D3
#define PIN_D4 MM100_IN_D4
#define PIN_E1 MM100_INJ1
#define PIN_E3 MM100_IN_D1
#define PIN_F2 MM100_UART8_TX
#define PIN_G3 MM100_OUT_PWM1
#define PIN_G4 MM100_OUT_PWM2
#define PIN_H1 MM100_INJ6
#define PIN_H2 MM100_INJ7
#define PIN_H3 MM100_IN_AUX4_ANALOG
